services:
  frontend:
    build: ./person-details-fe
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3000/api  # Use backend's service name instead of a static port

  backend:
    build: ./person-details-be
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - DB_USER=admin
      - DB_HOST=database
      - DB_NAME=persons_db
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - CSV_FILE_PATH=/app/src/data/persons.csv  # Ensure CSV file is read correctly

  database:
    image: postgres
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persons_db
    volumes:
      - ./person-details-be/database/init.sql:/docker-entrypoint-initdb.d/init.sql