version: "3.8"

services:
  frontend:
    build: ./person-details-fe
    ports:
      - "${FRONTEND_PORT:-5173}:80"  # Expose frontend on a fixed port
    depends_on:
      - backend
    env_file:
      - ./person-details-fe/.env  # Ensure frontend environment variables are loaded

  backend:
    build: ./person-details-be
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    depends_on:
      - database
    env_file:
      - ./person-details-be/.env  # Use .env file for backend

  database:
    image: postgres
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persons_db
    volumes:
      - ./person-details-be/database/init.sql:/docker-entrypoint-initdb.d/init.sql
